require 'rspec/types/unidom/party/china/blood_group_spec'
require 'rspec/types/unidom/party/china/business_registration_spec'
require 'rspec/types/unidom/party/china/ethnicity_alphabetic_spec'
require 'rspec/types/unidom/party/china/ethnicity_numeric_spec'
require 'rspec/types/unidom/party/china/formal_schooling_spec'
require 'rspec/types/unidom/party/china/marital_status_spec'
require 'rspec/types/unidom/party/china/political_affiliation_spec'
require 'rspec/types/unidom/party/china/religion_faith_spec'
