enum:

  # GB/T 3304-1991
  unidom_china_ethnicity_alphabetic:
    han:
      code: HA
      numeric_code: '01'
    mongol:
      code: MG
      numeric_code: '02'
    hui:
      code: HU
      numeric_code: '03'
    tibetan:
      code: ZA
      numeric_code: '04'
    uygur:
      code: UG
      numeric_code: '05'
    miao:
      code: MH
      numeric_code: '06'
    yi:
      code: YI
      numeric_code: '07'
    zhuang:
      code: ZH
      numeric_code: '08'
    buyei:
      code: BY
      numeric_code: '09'
    korean:
      code: CS
      numeric_code: '10'
    man:
      code: MA
      numeric_code: '11'
    dong:
      code: DO
      numeric_code: '12'
    yao:
      code: YA
      numeric_code: '13'
    bai:
      code: BA
      numeric_code: '14'
    tujia:
      code: TJ
      numeric_code: '15'
    hani:
      code: HN
      numeric_code: '16'
    kazak:
      code: KZ
      numeric_code: '17'
    dai:
      code: DA
      numeric_code: '18'
    li:
      code: LI
      numeric_code: '19'
    lisu:
      code: LS
      numeric_code: '20'
    va:
      code: VA
      numeric_code: '21'
    she:
      code: SH
      numeric_code: '22'
    gaoshan:
      code: GS
      numeric_code: '23'
    lahu:
      code: LH
      numeric_code: '24'
    sui:
      code: SU
      numeric_code: '25'
    dongxiang:
      code: DX
      numeric_code: '26'
    nazi:
      code: NX
      numeric_code: '27'
    jingpo:
      code: JP
      numeric_code: '28'
    kirgiz:
      code: KG
      numeric_code: '29'
    tu:
      code: TU
      numeric_code: '30'
    daur:
      code: DU
      numeric_code: '31'
    mulao:
      code: ML
      numeric_code: '32'
    qiang:
      code: QI
      numeric_code: '33'
    blang:
      code: BL
      numeric_code: '34'
    salar:
      code: SL
      numeric_code: '35'
    maonan:
      code: MN
      numeric_code: '36'
    gelao:
      code: GL
      numeric_code: '37'
    xibe:
      code: XB
      numeric_code: '38'
    achang:
      code: AC
      numeric_code: '39'
    pumi:
      code: PM
      numeric_code: '40'
    tajik:
      code: TA
      numeric_code: '41'
    nu:
      code: NU
      numeric_code: '42'
    uzbek:
      code: UZ
      numeric_code: '43'
    russ:
      code: RS
      numeric_code: '44'
    ewenki:
      code: EW
      numeric_code: '45'
    deang:
      code: DE
      numeric_code: '46'
    bonan:
      code: BN
      numeric_code: '47'
    yugur:
      code: YG
      numeric_code: '48'
    gin:
      code: GI
      numeric_code: '49'
    tatar:
      code: TT
      numeric_code: '50'
    derung:
      code: DR
      numeric_code: '51'
    oroqen:
      code: OR
      numeric_code: '52'
    hezhen:
      code: HZ
      numeric_code: '53'
    monba:
      code: MB
      numeric_code: '54'
    lhoba:
      code: LB
      numeric_code: '55'
    jino:
      code: JN
      numeric_code: '56'

  # GB/T 3304-1991
  unidom_china_ethnicity_numeric:
    han:
      code: '01'
      alphabetic_code: HA
    mongol:
      code: '02'
      alphabetic_code: MG
    hui:
      code: '03'
      alphabetic_code: HU
    tibetan:
      code: '04'
      alphabetic_code: ZA
    uygur:
      code: '05'
      alphabetic_code: UG
    miao:
      code: '06'
      alphabetic_code: MH
    yi:
      code: '07'
      alphabetic_code: YI
    zhuang:
      code: '08'
      alphabetic_code: ZH
    buyei:
      code: '09'
      alphabetic_code: BY
    korean:
      code: '10'
      alphabetic_code: CS
    man:
      code: '11'
      alphabetic_code: MA
    dong:
      code: '12'
      alphabetic_code: DO
    yao:
      code: '13'
      alphabetic_code: YA
    bai:
      code: '14'
      alphabetic_code: BA
    tujia:
      code: '15'
      alphabetic_code: TJ
    hani:
      code: '16'
      alphabetic_code: HN
    kazak:
      code: '17'
      alphabetic_code: KZ
    dai:
      code: '18'
      alphabetic_code: DA
    li:
      code: '19'
      alphabetic_code: LI
    lisu:
      code: '20'
      alphabetic_code: LS
    va:
      code: '21'
      alphabetic_code: VA
    she:
      code: '22'
      alphabetic_code: SH
    gaoshan:
      code: '23'
      alphabetic_code: GS
    lahu:
      code: '24'
      alphabetic_code: LH
    sui:
      code: '25'
      alphabetic_code: SU
    dongxiang:
      code: '26'
      alphabetic_code: DX
    nazi:
      code: '27'
      alphabetic_code: NX
    jingpo:
      code: '28'
      alphabetic_code: JP
    kirgiz:
      code: '29'
      alphabetic_code: KG
    tu:
      code: '30'
      alphabetic_code: TU
    daur:
      code: '31'
      alphabetic_code: DU
    mulao:
      code: '32'
      alphabetic_code: ML
    qiang:
      code: '33'
      alphabetic_code: QI
    blang:
      code: '34'
      alphabetic_code: BL
    salar:
      code: '35'
      alphabetic_code: SL
    maonan:
      code: '36'
      alphabetic_code: MN
    gelao:
      code: '37'
      alphabetic_code: GL
    xibe:
      code: '38'
      alphabetic_code: XB
    achang:
      code: '39'
      alphabetic_code: AC
    pumi:
      code: '40'
      alphabetic_code: PM
    tajik:
      code: '41'
      alphabetic_code: TA
    nu:
      code: '42'
      alphabetic_code: NU
    uzbek:
      code: '43'
      alphabetic_code: UZ
    russ:
      code: '44'
      alphabetic_code: RS
    ewenki:
      code: '45'
      alphabetic_code: EW
    deang:
      code: '46'
      alphabetic_code: DE
    bonan:
      code: '47'
      alphabetic_code: BN
    yugur:
      code: '48'
      alphabetic_code: YG
    gin:
      code: '49'
      alphabetic_code: GI
    tatar:
      code: '50'
      alphabetic_code: TT
    derung:
      code: '51'
      alphabetic_code: DR
    oroqen:
      code: '52'
      alphabetic_code: OR
    hezhen:
      code: '53'
      alphabetic_code: HZ
    monba:
      code: '54'
      alphabetic_code: MB
    lhoba:
      code: '55'
      alphabetic_code: LB
    jino:
      code: '56'
      alphabetic_code: JN

  # GB/T 4766-1984 ->
  # GB/T 2261.2-2003
  unidom_china_marital_status:
    unmarried:
      code: '10'
    married:
      code: '20'
    first_marriage:
      code: '21'
    remarriage:
      code: '22'
    former_marriage_restoration:
      code: '23'
    widowed:
      code: '30'
    divorce:
      code: '40'
    unspecified:
      code: '90'

  # GB/T 4762-1984
  unidom_china_political_affiliation:
    communist_party_member:
      code: '01'
    communist_party_probationary_member:
      code: '02'
    communist_youth_league_member:
      code: '03'
    kuomintang_revolutionary_committee_member:
      code: '04'
    democratic_league_member:
      code: '05'
    democratic_national_construction_association_member:
      code: '06'
    promoting_democracy_association_member:
      code: '07'
    peasants_and_worker_democratic_party_member:
      code: '08'
    public_interest_party_member:
      code: '09'
    jiusan_society_member:
      code: '10'
    taiwan_democratic_self_government_league_member:
      code: '11'
    independent_democrat:
      code: '12'
    masses:
      code: '13'

  # GA 214.12-2004
  unidom_china_religion_faith:
    no_religion:
      code: '00'
    buddhism:
      code: '10'
    lamaism:
      code: '20'
    taoism:
      code: '30'
    catholicism:
      code: '40'
    christian:
      code: '50'
    orthodox:
      code: '60'
    islam:
      code: '70'
    other:
      code: '99'

  # GB/T 4658-2006
  unidom_china_formal_schooling:

    postgraduate_education:
      code: '10'
    doctor_graduation:
      code: '11'
    doctor_completion:
      code: '12'
    doctor_incomplete_attendance:
      code: '13'
    master_graduation:
      code: '14'
    master_completion:
      code: '15'
    master_incomplete_attendance:
      code: '16'
    graduate_class_graduation:
      code: '17'
    graduate_class_completion:
      code: '18'
    graduate_class_incomplete_attendance:
      code: '19'

    university_college_education:
      code: '20'
    university_graduation:
      code: '21'
    university_completion:
      code: '22'
    university_incomplete_attendance:
      code: '23'
    undergraduate_class_graduation:
      code: '28'
    college_graduation:
      code: '31'
    college_completion:
      code: '32'
    college_incomplete_attendance:
      code: '33'

    secondary_vocational_education:
      code: '40'
    secondary_specialized_school_graduation:
      code: '41'
    secondary_specialized_school_completion:
      code: '42'
    secondary_specialized_school_incomplete_attendance:
      code: '43'
    vocational_high_school_graduation:
      code: '44'
    vocational_high_school_completion:
      code: '45'
    vocational_high_school_incomplete_attendance:
      code: '46'
    technician_school_graduation:
      code: '47'
    technician_school_completion:
      code: '48'
    technician_school_incomplete_attendance:
      code: '49'

    senior_school_education:
      code: '60'
    senior_school_graduation:
      code: '61'
    senior_school_completion:
      code: '62'
    senior_school_incomplete_attendance:
      code: '63'

    junior_school_education:
      code: '70'
    junior_school_graduation:
      code: '71'
    junior_school_incomplete_attendance:
      code: '73'

    primary_school_education:
      code: '80'
    primary_school_graduation:
      code: '81'
    primary_school_incomplete_attendance:
      code: '83'

    other:
      code: '90'

  # GA/T 2000.37-2014
  unidom_china_blood_group:
    unspecified:
      code: '0'
    a_type:
      code: '1'
    b_type:
      code: '2'
    o_type:
      code: '3'
    ab_type:
      code: '4'
    other:
      code: '9'

  # 关于划分企业登记注册类型的规定 http://www.stats.gov.cn/tjsj/tjbz/200610/t20061018_8657.html
  # 关于“个体经营”登记注册类型分类及代码的通知 国统办字（1999）2号 http://www.stats.gov.cn/tjsj/tjbz/200611/t20061123_8663.html
  unidom_china_business_registration:

    domestically_funded_company:
      code: '100'
    state_owned_enterprise:
      code: '110'
    collective_owned_enterprise:
      code: '120'
    joint_stock_cooperative_enterprise:
      code: '130'
    joint_ownership_enterprise:
      code: '140'
    limited_liability_company:
      code: '150'
    joint_stock_limited_company:
      code: '160'
    private_company:
      code: '170'
    other_domestically_funded:
      code: '190'

    taiwan_hk_macao_funded_enterprise:
      code: '200'
    sino_taiwan_hk_macao_equity_joint_venture:
      code: '210'
    sino_taiwan_hk_macao_contractual_joint_venture:
      code: '220'
    taiwan_hk_macao_equity_joint_venture:
      code: '230'
    taiwan_hk_macao_funded_joint_stock_limited_company:
      code: '240'
    other_taiwan_hk_macao_funded:
      code: '290'

    foreign_funded_enterprise:
      code: '300'
    sino_foreign_equity_joint_venture:
      code: '310'
    sino_foreign_contractual_joint_venture:
      code: '320'
    foreign_foreign_equity_joint_venture:
      code: '330'
    foreign_funded_joint_stock_limited_company:
      code: '340'
    other_foreign_funded:
      code: '390'

    self_employed_business:
      code: '400'
    getihu:
      code: '410'
    gerenhehuo:
      code: '420'
